
#spring:
#  cloud:
#    vault:
#      enabled: true
#      authentication: TOKEN
#      token: root
#      scheme: http
#      uri: http://localhost:8200
#      connection-timeout: 5000
#      read-timeout: 15000
#      kv:
#        application-name: application
#        enabled: true
#        default-context: application
#        profile-separator: '/'
